name: Deploy static Ebsite to s3

on:
  push:
     branches:
       -main

jobs:
  Deploy:
     runs-on: ubuntu-latest


     steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/ Configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_access_key_id}}
          aws-secret-access-key: ${{ secrets.AWS_access_key_key}}
          aws-region: ${{ secrets.AWS_region}}
      
      - name: Sync files to s3 
        runs:
          aws s3 sync . s3 ://${{ secrets.S3_bucket}} --delete --exclude ".git/*" --exclude ".github/*"
